project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:
  title: "Soilwise project FAIR Strategy"
  repo-url: https://github.com/soilwise-he/soilwise-fair-strategy
  repo-actions: [edit, issue]
  navbar:
    logo: https://avatars.githubusercontent.com/u/144736920?s=200&v=4
    logo-href: https://www.soilwise-he.eu
    logo-alt: Soilwise logo
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: Guideline Overview 
        href: General_Guidelines.md
      - text: Use Cases
        href: use-cases/index.md

  page-footer:
    right: 
      - text: The project receives funding from the European Unionâ€™s HORIZON Innovation Actions 2022 under grant agreement No. 101112838
        href: https://cordis.europa.eu/project/id/101112838

